/**
 * Lista de países para el formulario de recepción.
 * Los primeros son los de origen más frecuente en la posada, para que el
 * huésped no tenga que recorrer todo el desplegable en la tablet.
 */
export const PAISES_FRECUENTES = [
  "Uruguay",
  "Argentina",
  "Brasil",
  "Chile",
  "Paraguay",
] as const;

export const PAISES_RESTANTES = [
  "Alemania",
  "Australia",
  "Austria",
  "Bélgica",
  "Bolivia",
  "Canadá",
  "China",
  "Colombia",
  "Corea del Sur",
  "Costa Rica",
  "Cuba",
  "Dinamarca",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eslovaquia",
  "Eslovenia",
  "España",
  "Estados Unidos",
  "Estonia",
  "Filipinas",
  "Finlandia",
  "Francia",
  "Grecia",
  "Guatemala",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irlanda",
  "Islandia",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Letonia",
  "Lituania",
  "Luxemburgo",
  "Malasia",
  "Marruecos",
  "México",
  "Nicaragua",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Países Bajos",
  "Panamá",
  "Perú",
  "Polonia",
  "Portugal",
  "Puerto Rico",
  "Reino Unido",
  "República Checa",
  "República Dominicana",
  "Rumania",
  "Rusia",
  "Sudáfrica",
  "Suecia",
  "Suiza",
  "Tailandia",
  "Turquía",
  "Ucrania",
  "Venezuela",
  "Vietnam",
  "Otro",
] as const;

export const PAISES: readonly string[] = [
  ...PAISES_FRECUENTES,
  ...PAISES_RESTANTES,
];
